### ISSUE TITLE
[Bug] SkeletonESP

### ISSUE THREAD

**Issue by necrophili** [C10udburst/meteor-rejects#6]
- [x] if you use freecam you don’t see your own Skeleton ESP.
- [ ] if multiple players are standing close to eachother and only one of them swim their arm, all of their Skeleton ESP arm will swing instead.

**Comment by necrophili** [comment]
So I saw this being fixed in the 1.17 section, is the other features and bug fixes gonna be added to the 1.16 branch or nah

**Comment by C10udburst** [comment]
nah, I fixed SkeletonESP not working at all in 1.17 so that i guess also fixed this issue. I won't fix 1.16 because:
1. Rendering was changed in 1.17, so backporting it to 1.16 would take a long time
2. 1.16 is kinda discontinued already, even meteor devs suggest using 1.17 builds, only reason there is no release is because of baritone
